### ISSUE TITLE
Publish in bower

### ISSUE THREAD

**Issue by christophehurpeau** [es-shims/es7-shim#1]
Could you publish it to bower too ?
Thank you

**Comment by ljharb** [comment]
I've done this.

However, `bower` offers nothing over `npm` itself, and it's silly to continue using `bower` at this point (for a long time now) - you're strongly advised to use `npm` - `npm` is for everything.

**Comment by christophehurpeau** [comment]
I completely agree, but I need it for a project that's not mine. Thanks !
