### ISSUE TITLE
browser.js or es7-shim.browser.js

### ISSUE THREAD

**Issue by calvinhuang** [es-shims/es7-shim#15]
The .bower.json file specifies "es7-shim.browser.js" as the entry point, as does component.json. However, the bower package only comes with "browser.js" (which is what is specified in package.json).

So when grunt-wiredep injects the following script tag into the "bower:js" section, it results in a 404 error:
`<script src="bower_components/es7-shim/es7-shim.browser.js"></script>`.

**Comment by ljharb** [comment]
I don't have a bower.json file here as there's no reason anyone should be supporting or using bower. If one exists, then someone other than I published it on bower. It should be removed.

There's a "browser" entry point in package.json, which browserify/webpack should be able to pick up when the package is properly npm-installed.

**Comment by JakeChampion** [comment]
https://github.com/es-shims/es7-shim/blob/master/bower.json

**Comment by ljharb** [comment]
hm, i didn't see it on master

**Comment by ljharb** [comment]
Thanks, will fix.

**Comment by ljharb** [comment]
Apologies for the curt initial response. I didn't recall that I had a bower.json in this repo.

It should now be fixed (for component too) but I highly discourage using bower for this or any project in 2016, or in any year where npm exists.

**Comment by calvinhuang** [comment]
No worries. It does feel redundant to use bower on top of npm. I'll look into how I can modify my workflow and tooling (namely, the yeoman generators that I'm accustomed to scaffolding with) to avoid using bower.
