### ISSUE TITLE
Remove the toJSON shims

### ISSUE THREAD

**Issue by webbedspace** [es-shims/es7-shim#19]
[Rejected by TC39, like RegExp.escape](https://github.com/rwaldron/tc39-notes/blob/22f0fe10fda47225b91ba42fa1c1009c88a1057c/es7/2016-03/march-31.md#mapprototypetojsonsetprototypetojson)

**Comment by ljharb** [comment]
Technically ES7 is finalized, and only contains `Array#includes` out of what this shim provides. Rather than remove them, and make an ES2017 shim, etc, I'm working on an alternative to replace this module.

**Comment by ljharb** [comment]
Done in 9f61577dd10c48f02ffe0f8aebdc706a2fd4f1dd
