### ISSUE TITLE
Adding es7-shim to Karma.conf.js

### ISSUE THREAD

**Issue by DNR500** [es-shims/es7-shim#23]
Hi,

using es5 and es6 shims previously I've been able to add these shims to my karma test runner using..

https://github.com/radify/karma-es6-shim

Could you provide any advice on how best to approach adding es7-shim support to my karma runner?

Thanks

**Comment by ljharb** [comment]
The es5-shim and es6-shim automatically install themselves in the environment - the es7-shim does not. However, when browserified (or webpacked), it should do the same. Alternatively, you can reference `es7-shim/browser` as in that karma config.
